
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.font_manager as fm
import json
import textwrap

# 設定中文字型
font_path = r'C:\Windows\Fonts\msjh.ttc'
prop_bold = fm.FontProperties(fname=r'C:\Windows\Fonts\msjhbd.ttc')
prop = fm.FontProperties(fname=font_path)

# 圖表設定
width, height = 1200, 1600
dpi = 100
fig, ax = plt.subplots(figsize=(width/dpi, height/dpi), dpi=dpi)
ax.set_facecolor('#121212')  # 非常深的背景
fig.patch.set_facecolor('#121212')
ax.axis('off')

# 模擬讀取 Markdown 資訊 (因為解析 Markdown 比較麻煩，這裡直接用我們已知的一致資訊)
# 這樣可以確保圖片內容與 image/Home_analysis.md 和 maximize_view_flowchart.png 一致
report_data = {
    "title": "最大化窗外視野 (Maximize View)",
    "subtitle": "Dynamo 技術分析報告 | v3.4",
    "date": "2026-02-19",
    "stats": [
        ("節點總數 (Nodes)", "127", "#00bcd4"),
        ("連線總數 (Connectors)", "158", "#e91e63"),
        ("複雜度 (Complexity)", "⭐⭐⭐⭐", "#ffeb3b")
    ],
    "inputs": [
        "1. 選取房間 (Select Room)",
        "2. 選取計算元素 (Select Elements)",
        "3. 選取窗戶/帷幕 (Select Windows)",
        "4. 選取障礙物 (Select Obstacles)",
        "5. 設定檢視點 (Viewer Position X,Y)"
    ],
    "logic": [
        "1. 讀取房間邊界與障礙物幾何",
        "2. 產生視線向量 (Python Script)",
        "3. 檢測障礙物遮擋 (IsIntersect)",
        "4. 計算視野品質分數 (0-100)",
        "5. 視覺化顏色映射 (Cyan-Magenta)"
    ],
    "outputs": [
        "1. 窗外視野分數 (View Score)",
        "2. 到窗戶的距離 (Distance to Window)",
        "3. 與窗戶的平均角度 (Average Angle)",
        "4. 幾何視覺化顯示 (Geometry Color)"
    ]
}

# 繪製標題區
header_height = 0.85
ax.text(0.5, 0.95, report_data["title"], ha='center', va='center', fontsize=36, color='white', fontproperties=prop_bold)
ax.text(0.5, 0.91, report_data["subtitle"], ha='center', va='center', fontsize=18, color='#aaaaaa', fontproperties=prop)

# 繪製數據儀表板
for i, (label, val, color) in enumerate(report_data["stats"]):
    x = 0.2 + i * 0.3
    y = 0.82
    # 圓圈背景
    circle = patches.Circle((x, y), 0.12, linewidth=2, edgecolor=color, facecolor='none', alpha=0.8)
    ax.add_patch(circle)
    # 數值
    ax.text(x, y+0.01, val, ha='center', va='center', fontsize=32, color='white', fontproperties=prop_bold)
    # 標籤
    ax.text(x, y-0.08, label, ha='center', va='center', fontsize=12, color=color, fontproperties=prop)

# 分隔線
ax.plot([0.1, 0.9], [0.68, 0.68], color='#333333', linewidth=2)

def draw_list_section(x, y, title, items, color):
    # 標題
    ax.text(x, y, title, ha='left', va='center', fontsize=20, color=color, fontproperties=prop_bold)
    # 列表
    for i, item in enumerate(items):
        ax.text(x + 0.02, y - 0.05 - (i * 0.04), f"• {item}", ha='left', va='center', fontsize=14, color='#dddddd', fontproperties=prop)

# 繪製詳細內容區
draw_list_section(0.15, 0.62, "📥 輸入參數 (Inputs)", report_data["inputs"], "#00bcd4")
draw_list_section(0.15, 0.38, "⚙️ 執行邏輯 (Logic)", report_data["logic"], "#ffeb3b")
draw_list_section(0.15, 0.14, "📤 產出結果 (Outputs)", report_data["outputs"], "#e91e63")

# 頁尾
ax.text(0.5, 0.02, "Generated by Dynamo MCP Agent", ha='center', va='center', fontsize=10, color='#444444', fontproperties=prop)

# 儲存
output_file = "image/Home_analysis_card.png"
plt.tight_layout()
plt.savefig(output_file, dpi=dpi, bbox_inches='tight', facecolor='#121212')
print(f"Report card saved to {output_file}")
